parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            bool $logAppEnable: "%env(LOG_APP_ENABLE)%"

    App\:
        resource: "../src/"
        exclude:
            - "../src/DependencyInjection/"
            - "../src/Entity/"
            - "../src/Kernel.php"
